import { NextRequest, NextResponse } from "next/server";
import { db } from "../../../lib/db";
import { currentUser } from "../../../lib/auth";
function legacyKey(req: NextRequest){ return req.headers.get("x-pricematch-user")?.trim() || "demo-user"; }
export async function GET(req:NextRequest){
  const user=await currentUser(); const where=user?{userId:user.id,active:true}:{userKey:legacyKey(req),active:true};
  const items=await db.watchlistItem.findMany({where,include:{product:{include:{offers:true}}},orderBy:{createdAt:"desc"}});
  return NextResponse.json(items.map(i=>({id:i.id,canonicalId:i.product.canonicalId,title:i.product.title,imageUrl:i.product.imageUrl,targetPrice:i.targetPrice,lastAlertedPrice:i.lastAlertedPrice,lastCheckedAt:i.lastCheckedAt,createdAt:i.createdAt,lowestTotal:Math.min(...i.product.offers.map(o=>o.price+(o.shipping??0)),Infinity)})));
}
export async function POST(req:NextRequest){try{const body=await req.json();if(!body.canonicalId)return NextResponse.json({error:"canonicalId is required."},{status:400});const product=await db.product.findUnique({where:{canonicalId:body.canonicalId}});if(!product)return NextResponse.json({error:"Product not found."},{status:404});const targetPrice=body.targetPrice==null||body.targetPrice===""?null:Number(body.targetPrice);if(targetPrice!==null&&(!Number.isFinite(targetPrice)||targetPrice<0))return NextResponse.json({error:"Target price must be a valid number."},{status:400});const user=await currentUser();let item;if(user){const existing=await db.watchlistItem.findFirst({where:{userId:user.id,productId:product.id}});item=existing?await db.watchlistItem.update({where:{id:existing.id},data:{targetPrice,active:true}}):await db.watchlistItem.create({data:{userId:user.id,productId:product.id,targetPrice}});}else{item=await db.watchlistItem.upsert({where:{userKey_productId:{userKey:legacyKey(req),productId:product.id}},create:{userKey:legacyKey(req),productId:product.id,targetPrice},update:{targetPrice,active:true}});}return NextResponse.json({id:item.id,canonicalId:product.canonicalId,targetPrice:item.targetPrice},{status:201});}catch{return NextResponse.json({error:"Unable to save watchlist item."},{status:500});}}
export async function DELETE(req:NextRequest){const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"id is required."},{status:400});const user=await currentUser();await db.watchlistItem.deleteMany({where:user?{id,userId:user.id}:{id,userKey:legacyKey(req)}});return NextResponse.json({ok:true});}
