CREATE TABLE "User" ("id" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE TABLE "Session" ("id" TEXT NOT NULL, "token" TEXT NOT NULL, "userId" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Session_token_key" ON "Session"("token");
CREATE INDEX "Session_userId_expiresAt_idx" ON "Session"("userId","expiresAt");
CREATE TABLE "Product" ("id" TEXT NOT NULL, "canonicalId" TEXT NOT NULL, "title" TEXT NOT NULL, "brand" TEXT, "model" TEXT, "imageUrl" TEXT, "attributesJson" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Product_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Product_canonicalId_key" ON "Product"("canonicalId");
CREATE TABLE "ProductIdentifier" ("id" TEXT NOT NULL, "type" TEXT NOT NULL, "value" TEXT NOT NULL, "productId" TEXT NOT NULL, CONSTRAINT "ProductIdentifier_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ProductIdentifier_type_value_key" ON "ProductIdentifier"("type","value");
CREATE INDEX "ProductIdentifier_productId_idx" ON "ProductIdentifier"("productId");
CREATE TABLE "RetailerSource" ("id" TEXT NOT NULL, "key" TEXT NOT NULL, "name" TEXT NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "RetailerSource_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "RetailerSource_key_key" ON "RetailerSource"("key");
CREATE TABLE "Offer" ("id" TEXT NOT NULL, "productId" TEXT NOT NULL, "retailerId" TEXT NOT NULL, "retailerSku" TEXT, "title" TEXT NOT NULL, "price" DOUBLE PRECISION NOT NULL, "shipping" DOUBLE PRECISION, "currency" TEXT NOT NULL DEFAULT 'USD', "availability" TEXT NOT NULL DEFAULT 'unknown', "url" TEXT NOT NULL, "matchConfidence" DOUBLE PRECISION NOT NULL, "matchReason" TEXT, "firstSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Offer_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Offer_productId_retailerId_retailerSku_key" ON "Offer"("productId","retailerId","retailerSku");
CREATE INDEX "Offer_productId_lastSeenAt_idx" ON "Offer"("productId","lastSeenAt");
CREATE TABLE "PriceSnapshot" ("id" TEXT NOT NULL, "offerId" TEXT NOT NULL, "price" DOUBLE PRECISION NOT NULL, "shipping" DOUBLE PRECISION, "total" DOUBLE PRECISION NOT NULL, "currency" TEXT NOT NULL DEFAULT 'USD', "availability" TEXT NOT NULL DEFAULT 'unknown', "capturedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PriceSnapshot_pkey" PRIMARY KEY ("id"));
CREATE INDEX "PriceSnapshot_offerId_capturedAt_idx" ON "PriceSnapshot"("offerId","capturedAt");
CREATE TABLE "WatchlistItem" ("id" TEXT NOT NULL, "userKey" TEXT, "userId" TEXT, "productId" TEXT NOT NULL, "targetPrice" DOUBLE PRECISION, "active" BOOLEAN NOT NULL DEFAULT true, "lastAlertedPrice" DOUBLE PRECISION, "lastCheckedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "WatchlistItem_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "WatchlistItem_userKey_productId_key" ON "WatchlistItem"("userKey","productId");
CREATE INDEX "WatchlistItem_userId_active_idx" ON "WatchlistItem"("userId","active");
CREATE INDEX "WatchlistItem_userKey_active_idx" ON "WatchlistItem"("userKey","active");
CREATE TABLE "NotificationLog" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "watchlistItemId" TEXT NOT NULL, "channel" TEXT NOT NULL, "status" TEXT NOT NULL, "subject" TEXT NOT NULL, "message" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "NotificationLog_pkey" PRIMARY KEY ("id"));
CREATE INDEX "NotificationLog_userId_createdAt_idx" ON "NotificationLog"("userId","createdAt");
CREATE TABLE "DealClick" ("id" TEXT NOT NULL, "offerId" TEXT NOT NULL, "userId" TEXT, "retailer" TEXT NOT NULL, "destinationHost" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "DealClick_pkey" PRIMARY KEY ("id"));
CREATE INDEX "DealClick_offerId_createdAt_idx" ON "DealClick"("offerId","createdAt");
CREATE INDEX "DealClick_retailer_createdAt_idx" ON "DealClick"("retailer","createdAt");
CREATE TABLE "AnalyticsEvent" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "userId" TEXT, "productId" TEXT, "retailerId" TEXT, "sessionKey" TEXT, "path" TEXT, "metadataJson" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AnalyticsEvent_pkey" PRIMARY KEY ("id"));
CREATE INDEX "AnalyticsEvent_name_createdAt_idx" ON "AnalyticsEvent"("name","createdAt");
CREATE INDEX "AnalyticsEvent_productId_createdAt_idx" ON "AnalyticsEvent"("productId","createdAt");
CREATE INDEX "AnalyticsEvent_retailerId_createdAt_idx" ON "AnalyticsEvent"("retailerId","createdAt");
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProductIdentifier" ADD CONSTRAINT "ProductIdentifier_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Offer" ADD CONSTRAINT "Offer_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Offer" ADD CONSTRAINT "Offer_retailerId_fkey" FOREIGN KEY ("retailerId") REFERENCES "RetailerSource"("id") ON DELETE NO ACTION ON UPDATE CASCADE;
ALTER TABLE "PriceSnapshot" ADD CONSTRAINT "PriceSnapshot_offerId_fkey" FOREIGN KEY ("offerId") REFERENCES "Offer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WatchlistItem" ADD CONSTRAINT "WatchlistItem_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WatchlistItem" ADD CONSTRAINT "WatchlistItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "NotificationLog" ADD CONSTRAINT "NotificationLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DealClick" ADD CONSTRAINT "DealClick_offerId_fkey" FOREIGN KEY ("offerId") REFERENCES "Offer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DealClick" ADD CONSTRAINT "DealClick_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AnalyticsEvent" ADD CONSTRAINT "AnalyticsEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AnalyticsEvent" ADD CONSTRAINT "AnalyticsEvent_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AnalyticsEvent" ADD CONSTRAINT "AnalyticsEvent_retailerId_fkey" FOREIGN KEY ("retailerId") REFERENCES "RetailerSource"("id") ON DELETE SET NULL ON UPDATE CASCADE;
